# This configuration generates the bootstrap override files
--- 
:read_config:
- _versions.config.yaml
- _paths.config.yaml
# Comment the following to skip metadata from the data/ folder (the SQL files and wiki pages)
:modules:
- qsapp_source
:templates: 
#- basic
#- icon-maker
#- plist
#- packager
- default-override
:argv:
- '*'
:output: out/initial-overrides